label Buildroot on PineTab 2 v2.0
  kernel /Image
  devicetree /rk3566-pinetab2-v2.0.dtb
  initrd /rootfs.cpio
  append earlycon=uart8250,mmio32,0xfe660000 console=ttyS0,115200n8 root=/dev/mmcblk1p2 rw rootwait
